apiVersion: v1
kind: Namespace
metadata:
  name: dev2
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: dev2
  namespace: dev2
spec:
    type: Namespace
    pathname: dev2
---
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  annotations:
    apps.open-cluster-management.io/is-local-deployable: "false"
  name: sample-cr-configmap
  namespace: dev2
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      namespace: default
    data:
      purpose: for test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sub-configmap
spec:
  channel: dev2/dev2
  name: sub-configmap
  placement:
    clusters:
    - name: loca-cluster
    local: false
  overrides:
  - clusterName: /
    clusterOverrides:
    - path: metadata.labels
      value:
        app: app1
  - clusterName: local-cluster
    clusterOverrides:
    - path: metadata.labels
      value:
        app: app2
