apiVersion: apps/v1
kind: Deployment
metadata:
  name: pw-appsub-summary
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-operators-appsub-summary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: multicluster-operators-appsub-summary
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multicluster-operators-appsub-summary
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multicluster-operators-appsub-summary
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - command:
        - /usr/local/bin/appsubsummary
        - --v=1
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/phwu/appsub:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 600
          successThreshold: 1
          timeoutSeconds: 1
        name: pw-appsub-summary
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 600
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 750m
            memory: 2Gi
          requests:
            cpu: 150m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: multicluster-operators
      serviceAccountName: multicluster-operators
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: tmp
