---
apiVersion: apps.open-cluster-management.io/v1alpha1
kind: SubscriptionPackageStatus
metadata:
  labels:
    apps.open-cluster-management.io/cluster: test-cluster-<CLUSTER-NUM>
    apps.open-cluster-management.io/hosting-subscription: appsub-ns-<APPSUB-NUM>.appsub-<APPSUB-NUM>
  name: appsub-ns-<APPSUB-NUM>.appsub-<APPSUB-NUM>.status
  namespace: test-cluster-<CLUSTER-NUM>
statuses:
  packages:
    - name: serviceaccount-<PACKAGE-NUM>
      kind: ServiceAccount
      namespace: ns-sub-1
      phase: Deployed
      message: "service account deployed"
      lastUpdateTime: "2021-06-07T16:29:44Z"
    - name: clusterrole-<PACKAGE-NUM>
      kind: ClusterRole
      namespace: ns-sub-1
      phase: Deployed
      message: "cluster role deployed"
      lastUpdateTime: "2021-06-07T16:29:44Z"
    - name: clusterrolebinding-<PACKAGE-NUM>
      kind: ClusterRoleBinding
      namespace: ns-sub-1
      phase: Deployed
      message: "cluster role binding deployed"
      lastUpdateTime: "2021-06-07T16:29:44Z"
    - name: service-1
      pkgkind: Service
      pkgnamespace: ns-sub-<UPDATE-NUM>
      phase: Deployed
      message: "service deployed"
      lastUpdateTime: "2021-06-07T16:29:44Z"
    - name: deployment-1
      kind: Deployment
      namespace: ns-sub-<UPDATE-NUM>
      phase: Deployed
      message: "deployment deployed"
      lastUpdateTime: "2021-06-07T16:29:44Z"
