---
apiVersion: v1
kind: Namespace
metadata:
  name: appsub-ns-<APPSUB-NUM>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: appsub-ns-<APPSUB-NUM>
  name: appsub-<APPSUB-NUM>
spec:
  channel: sub004/ggithubcom-rokej-myapplication
  placement:
    local: false
