apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-operators-application
  namespace: multicluster-operators
  labels:
    name: multicluster-operators-application
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: multicluster-operators-application
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: multicluster-operators-application
    spec:
      containers:
      - command:
        - /usr/local/bin/multicluster-operators-placementrule
        - --alsologtostderr
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_LABEL
          value: multicluster-operators-application
        - name: OPERATOR_NAME
          value: multicluster-operators-placementrule
        image: quay.io/open-cluster-management/multicluster-operators-placementrule:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: multicluster-operators-placementrule
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - command:
        - /usr/local/bin/multicluster-operators-deployable
        - --alsologtostderr
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_LABEL
          value: multicluster-operators-application
        - name: OPERATOR_NAME
          value: multicluster-operators-deployable
        image: quay.io/open-cluster-management/multicluster-operators-deployable:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: multicluster-operators-deployable
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - command:
        - /usr/local/bin/multicluster-operators-channel
        - --alsologtostderr
        - --debug=true
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_LABEL
          value: multicluster-operators-application
        - name: OPERATOR_NAME
          value: multicluster-operators-channel
        image: quay.io/open-cluster-management/multicluster-operators-channel:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: multicluster-operators-channel
        ports:
        - containerPort: 9443
          name: chn-whk-server
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: multicluster-operators
      serviceAccountName: multicluster-operators
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
