apiVersion: v1                    
kind: Namespace
metadata:
  name: sub003
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-rokej-myapplication-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ggithubcom-rokej-myapplication
  namespace: sub003
spec:
  type: Git
  pathname: https://github.com/rokej/myapplication.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-tag: v2.0
    apps.open-cluster-management.io/reconcile-option: merge
  name: sub003-test-subscription-1
  namespace: sub003
spec:
  channel: sub003/ggithubcom-rokej-myapplication
  placement:
    local: true