---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/open-cluster-management/multicloud-operators-subscription.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: parentsub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-sub
  namespace: parentsub
  annotations: 
    apps.open-cluster-management.io/cluster-admin: "true"
    apps.open-cluster-management.io/github-path: test/e2e/github/nestedSubscription
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: ch-git/git
  placement:
    local: true
