---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns-helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git-helm
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: git-sub-app
  namespace: git-sub-ns-helm
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: git-sub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-helm
  namespace: ch-git-helm
  labels:
    name: git-sub
spec:
  type: Git
  pathname: https://github.com/open-cluster-management/multicloud-operators-subscription
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: git-sub-ns-helm
  labels:
    name: git-sub
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-helm-sub
  namespace: git-sub-ns-helm
  annotations:
    apps.open-cluster-management.io/github-path: test/github/helmcharts/chart1
  labels:
    name: git-sub
spec:
  channel: ch-git-helm/git-helm
  placement:
    placementRef: 
      name: towhichcluster
      kind: PlacementRule
