---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: git-sub-app
  namespace: git-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: git-sub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: ch-git
  labels:
    name: git-sub
spec:
  type: Git
  pathname: https://github.com/ianzhang366/acm-applifecycle-samples.git
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: default
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: towhichcluster
  namespace: default
  labels:
    name: git-sub
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: "In"
          values:
          - Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-sub
  labels:
    name: git-sub
  annotations:
    apps.open-cluster-management.io/github-path: git-ops/bookinfo/guestbook
spec:
  channel: ch-git/git
  placement:
    placementRef: 
      name: towhichcluster
      namespace: default
      kind: Placement
