---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-helm
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: helm-sub-app
  namespace: helm-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: helm-sub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm
  namespace: ch-helm
  labels:
    name: helm-sub
spec:
  type: HelmRepo
  pathname: https://ianzhang366.github.io/guestbook-chart/
  insecureSkipVerify: true
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: default
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: towhichcluster
  namespace: default
  labels:
    name: helm-sub
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: "In"
          values:
          - Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helm-sub
  labels:
    name: helm-sub
spec:
  channel: ch-helm/helm
  name: gbapp
  packageFilter:
    version: "0.1.0"
  placement:
    placementRef: 
      name: towhichcluster
      namespace: default
      kind: Placement
