---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ns-sub-app
  namespace: ns-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: ns-sub
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-test
  namespace: ch-ns
  labels:
    name: ns-sub
  annotations: 
    apps.open-cluster-management.io/deployables: "true"
data:
  AccessKeyID: YWRtaW4=
  SecretAccessKey: cGFzc3dvcmRhZG1pbg==
--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata: 
  name: payload-cfg-namespace-channel
  labels:
    name: ns-sub
    apps.open-cluster-management.io/channel: ns
    apps.open-cluster-management.io/channel-type: Namespace
  annotations: 
    apps.open-cluster-management.io/is-local-deployable: "false"
  namespace: default
spec: 
  channels: 
  - ns
  template: 
    apiVersion: v1
    data: 
      database: mongodb
    kind: ConfigMap
    metadata: 
      name: cfg-from-ch-qa
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ns
  namespace: ch-ns
  labels:
    name: ns-sub
spec:
  type: Namespace
  pathname: ch-ns
  sourceNamespaces:
    - default
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: ns-sub-ns
  labels:
    name: ns-sub
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ns-sub
  namespace: ns-sub-ns
  labels:
    name: ns-sub
spec:
  channel: ch-ns/ns
  placement:
    placementRef: 
      name: towhichcluster
      kind: PlacementRule
  timewindow:
    windowtype: "active"
    location: "America/Toronto"
    hours:
      - start: "9:00AM"
        end: "11:50AM"
      - start: "12:00PM"
        end: "6:30PM"
