---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ns-sub-app
  namespace: ns-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: ns-sub
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-test
  namespace: ch-ns
  labels:
    name: ns-sub
data:
  AccessKeyID: YWRtaW4=
  SecretAccessKey: cGFzc3dvcmRhZG1pbg==
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ns
  namespace: ch-ns
  labels:
    name: ns-sub
spec:
  type: Namespace
  pathname: ch-ns
  sourceNamespaces:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: default
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: towhichcluster
  namespace: default
  labels:
    name: ns-sub
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: "In"
          values:
          - Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ns-sub
  labels:
    name: ns-sub
spec:
  channel: ch-ns/ns
  placement:
    placementRef: 
      name: towhichcluster
      namespace: default
      kind: Placement
  timewindow:
    windowtype: "active"
    location: "America/Toronto"
    hours:
      - start: "9:00AM"
        end: "11:50AM"
      - start: "12:00PM"
        end: "6:30PM"
