---
apiVersion: v1
kind: Namespace
metadata:
  name: obj-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-obj
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: obj-sub-app
  namespace: obj-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: obj-sub
--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: deva
  namespace: ch-obj
  labels:
    name: obj-sub
spec:
  type: ObjectBucket
  pathname: http://ec2-100-26-232-156.compute-1.amazonaws.com:9000/deva
  sourceNamespaces:
    - default
  secretRef:
    name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev
  namespace: ch-obj
  labels:
    name: obj-sub
data:
  AccessKeyID: YWRtaW4=
  SecretAccessKey: cGFzc3dvcmRhZG1pbg==
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: default
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: towhichcluster
  namespace: default
  labels:
    name: obj-sub-ns
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: "In"
          values:
          - Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: obj-sub
  labels:
    name: obj-sub
spec:
  channel: ch-obj/deva
  placement:
    placementRef: 
      name: towhichcluster
      namespace: default
      kind: Placement
