apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: examples/remote-git-sub-op
  name: nginx-app-sub
  namespace: default
spec:
  channel: gitops-chn-ns/gitops
  placement:
    placementRef:
      kind: Placement
      name: nginx-demo-placement
      namespace: default
