apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-local-cluster
  namespace: default
spec:
  # apply to 1 cluster whoevers name not local-cluster
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: "NotIn"
          values:
          - local-cluster