kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicloud-operators-agent
subjects:
- kind: ServiceAccount
  name: multicloud-operators
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: multicloud-operators-agent
  apiGroup: rbac.authorization.k8s.io
