apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: git-gb
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: guestbook/all-in-one
    apps.open-cluster-management.io/reconcile-option: merge    
  name: appsub-<APPSUB-NUM>
  namespace: appsub-ns-<APPSUB-NUM>
spec:
  channel: channel1/ggithubcom-kubernetes-examples
  placement:
    placementRef:
      kind: PlacementRule
      name: git-gb-placement-1
---
