apiVersion: v1
kind: Namespace
metadata:
  name: channel1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ggithubcom-kubernetes-examples
  namespace: channel1
spec:
  pathname: https://github.com/kubernetes/examples.git
  type: GitHub
