apiVersion: v1
kind: Namespace
metadata:
  name: appsub-ns-<APPSUB-NUM>
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: git-gb-placement-1
  namespace: appsub-ns-<APPSUB-NUM>
spec:
  clusterReplicas: 2000
  clusterSelector: {}
---
