---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: default
spec:
  type: git
  pathname: https://github.com/stolostron/multicloud-operators-subscription.git
