apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-manager-agent
rules:
- apiGroups: ["apps.open-cluster-management.io"]
  resources: ["deployables"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.open-cluster-management.io"]
  resources: ["deployables/status"]
  verbs: ["update", "patch"]
