apiVersion: batch/v1
kind: Job
metadata:
  name: long-running-job
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: long-running-job
        image: busybox
        command: ["sleep",  "300"]
      restartPolicy: Never
  backoffLimit: 4

